// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnvgcykgxevtsugvyxdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhudmdjeWtneGV2dHN1Z3Z5eGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3NjgxNjksImV4cCI6MjA1MDM0NDE2OX0.rD8qDOpn7i0ioBYNUK1cFusmYL5UfgQli7Xk8FmvXoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);